import type { Product } from "@/types/product"

const products: Product[] = [
  {
    id: "massager-4d",
    slug: "masajeador-4d-portatil",
    name: "Masajeador Eléctrico Dedos 4D Portátil",
    shortDescription: "Alivia cuello, hombros y espalda al instante con tecnología de amasado 4D y calor. Inalámbrico, recargable y ultra silencioso.",
    longDescription: "Adiós a la tensión muscular. Este masajeador portátil combina 4 dedos de amasado que simulan la presión de manos humanas con calor terapéutico para eliminar contracturas, desinflamar tejidos y relajar los músculos más profundos. Diseñado para cuello, hombros, espalda, piernas y pies. Inalámbrico, recargable por USB y tan silencioso que lo puedes usar mientras trabajas o ves TV.",
    price: {
      normal: 45000,
      offer: 34990,
      bundle: {
        quantity: 2,
        price: 59990,
        label: "2x $59.990 (ahorras $9.990)",
      },
    },
    category: "masaje",
    brand: "Tecnofy",
    sku: "TEC-4D-001",
    images: [
      { src: "/images/hero.webp", alt: "Masajeador 4D portátil Tecnofy" },
      { src: "/images/offer.png", alt: "Masajeador 4D vista frontal" },
    ],
    gallery: [
      { src: "/images/detail-4.webp", alt: "Portátil y recargable", label: "Portátil y recargable" },
      { src: "/images/detail-2.webp", alt: "Aplicación en cuello", label: "Alivio en cuello y hombros" },
      { src: "/images/detail-1.webp", alt: "Dedos de amasado 4D", label: "Dedos de amasado 4D" },
      { src: "/images/solution.png", alt: "Aplicación versátil", label: "Aplicación versátil" },
    ],
    benefits: [
      { text: "Alivia cuello y hombros" },
      { text: "Reduce el estrés muscular" },
      { text: "Calor calmante integrado" },
      { text: "Inalámbrico y recargable" },
      { text: "Ultra silencioso" },
      { text: "Correa ajustable incluida" },
    ],
    features: [
      {
        title: "Elimina contracturas en minutos",
        description: "No es solo vibración. La tecnología 4D simula la presión de manos humanas para deshacer nudos musculares, combinado con calor terapéutico.",
        icon: "💆",
      },
      {
        title: "Calor que desinflama y relaja",
        description: "Activa el modo calor para mejorar la circulación, desinflamar los tejidos y potenciar el alivio muscular en cada sesión.",
        icon: "🔥",
      },
      {
        title: "Llega a cualquier zona dolorida",
        description: "Cuello, hombros, espalda, piernas o pies. La correa ajustable te permite enfocar el alivio justo donde más te duele. Inalámbrico y silencioso.",
        icon: "⚡",
      },
      {
        title: "Relájate sin preocupaciones",
        description: "Apagado automático a los 15 minutos para evitar sobreuso. Seguridad inteligente mientras te olvidas del dolor.",
        icon: "🛡️",
      },
    ],
    specs: [
      { label: "Tecnología", value: "Amasado 4D + Calor", icon: "🔄" },
      { label: "Alimentación", value: "USB Recargable", icon: "🔋" },
      { label: "Auto apagado", value: "15 minutos", icon: "⏱️" },
      { label: "Peso", value: "300 g (ultra ligero)", icon: "🏋️" },
      { label: "Ruido", value: "Ultra silencioso", icon: "🔇" },
      { label: "Portabilidad", value: "Inalámbrico / Compacto", icon: "🎒" },
    ],
    testimonials: [
      { name: "Andrea G.", location: "Valparaíso", rating: 5, text: "Pensé que era otro producto más pero el calor y los dedos 4D son increíbles. Se siente como un masaje real.", avatar: "/img/cliente-1.webp" },
      { name: "Carlos M.", location: "Santiago", rating: 5, text: "Trabajo en oficina 9 horas y siempre terminaba con el cuello tieso. Esto me cambió la vida, lo uso todos los días.", avatar: "/img/cliente-2.webp" },
      { name: "Camila R.", location: "Antofagasta", rating: 5, text: "Ideal para después del gym. Lo uso en los hombros y piernas. Bien potente y el calor es un plus enorme.", avatar: "/img/cliente-3.webp" },
    ],
    faqs: [
      { question: "¿Cómo alivia el dolor muscular?", answer: "Utiliza 4 puntos de presión que simulan el movimiento de amasado de manos humanas, combinado con calor suave. No es una simple vibración: realmente presiona y trabaja los músculos tensos." },
      { question: "¿Duele la función de calor?", answer: "Para nada. El calor es suave y regulado a una temperatura segura. Puedes activarlo o desactivarlo según tu preferencia." },
      { question: "¿Cuánto dura la batería?", answer: "Con una carga completa vía USB (aprox 1-2 horas) puedes usar varias sesiones de 15 minutos. Tiene apagado automático para ahorrar batería." },
      { question: "¿Cómo es el envío y el pago?", answer: "Hacemos envíos a todo Chile. El pago es contra entrega: recibes el producto, lo revisas y solo entonces pagas. Sin adelantos, sin riesgo." },
      { question: "¿En cuánto tiempo llega?", answer: "El tiempo de entrega es de 3 a 7 días hábiles dependiendo de tu comuna y región." },
      { question: "¿Tiene garantía?", answer: "Sí, todos nuestros productos cuentan con 3 meses de garantía. Si tienes cualquier problema, contáctanos por WhatsApp." },
    ],
    painPoints: [
      { icon: "💆‍♂️", title: "Cuello rígido", description: "Esa contractura molesta después de largas horas frente a la pantalla" },
      { icon: "🔥", title: "Hombros tensos", description: "La carga del estrés se acumula en los hombros generando puntos de dolor" },
      { icon: "⚡", title: "Espalda dolorida", description: "Tensión lumbar y dorsal que empeora con malas posturas" },
      { icon: "😫", title: "Estrés acumulado", description: "El cansancio físico y mental del día a día que no te deja descansar" },
    ],
    howItWorks: [
      { step: 1, title: "Carga", description: "Cárgalo vía USB (cable incluido). Una hora de carga te da varias sesiones de alivio." },
      { step: 2, title: "Coloca donde te duele", description: "Ajusta la correa en la zona con dolor: cuello, hombros, espalda o piernas." },
      { step: 3, title: "Relájate y olvídate del dolor", description: "Enciende, elige tu modo y deja que la tecnología 4D con calor elimine la tensión." },
    ],
    stock: 42,
    status: "active",
    tags: ["masaje", "4d", "calor", "cuello", "hombros", "espalda", "portatil"],
    seo: {
      title: "Masajeador 4D Portátil | Alivia tu dolor muscular — $34.990",
      description: "Elimina la tensión en cuello y hombros sin depender de nadie. Solución de amasado 4D con calor. $34.990 – Envío gratis a todo Chile – Pago contra entrega.",
      keywords: "alivio dolor muscular, tension cuello, contracturas, dolor hombros, relajacion muscular, pago contra entrega, envio gratis, Chile",
      ogImage: "/images/hero.webp",
    },
    createdAt: "2026-06-01",
    updatedAt: "2026-07-05",
    heroTitle: "¿Cuello y hombros <span class=\"text-[var(--primary)]\">destruidos</span> por el estrés?",
    heroTrustBadges: [
      { icon: "Alivio 4D", label: "Alivio 4D" },
      { icon: "Con calor", label: "Con calor" },
      { icon: "USB Recargable", label: "USB Recargable" },
      { icon: "Ultra silencioso", label: "Ultra silencioso" },
    ],
    solutionLabel: "La Solución",
    solutionTitle: "Alivia el dolor muscular <span class=\"text-[var(--primary)]\">donde y cuando quieras</span>",
    solutionImageLabel: "Alivio 4D · Calor · Portátil",
    galleryTitle: "Así es tu solución anti-dolor",
    galleryDescription: "Cada detalle está diseñado para darte el alivio muscular que necesitas",
    finalCtaTitle: "¿Listo para relajar tus músculos<br/>sin depender de nadie?",
    problemLabel: "¿Te sientes identificado?",
    problemTitle: "El estrés y la tensión no son normales",
    problemDescription: "Si pasas horas frente al computador, manejando o estudias, tus músculos te están pidiendo ayuda",
    offerDescription: "Aprovecha el descuento por lanzamiento y dile adiós al dolor — envío gratis a todo Chile",
    videoDemoTitle: "Míralo en acción",
    videoDemoDescription: "Un video vale más que mil fotos — mira lo fácil que es usarlo",
    videoDemo: [
      { src: "/video/demo-1.mp4", poster: "/video/demo-1.gif", label: "🧘 Uso en cuello y hombros" },
      { src: "/video/demo-2.mp4", poster: "/video/demo-2.gif", label: "🔥 Modo calor + amasado" },
    ],
  },
  {
    id: "minicamara-wifi",
    slug: "mini-camara-wifi",
    name: "Mini Cámara WiFi de Seguridad HD 1080p",
    shortDescription: "Protege tu hogar o negocio con esta cámara compacta WiFi. Visión nocturna, detección de movimiento y app gratuita.",
    longDescription: "Mini cámara WiFi de seguridad HD 1080p con visión nocturna por infrarrojo y detección de movimiento. Monitorea tu hogar, local comercial o bodega en tiempo real desde la app gratuita en tu celular. Ultra compacta, se instala en segundos y se conecta a tu red WiFi sin cables. Batería de larga duración o conexión directa a corriente para uso 24/7. Incluye garantía de 3 meses.",
    price: {
      normal: 39990,
      offer: 24990,
      bundle: {
        quantity: 2,
        price: 40000,
        label: "2x $40.000 (ahorras $9.980)",
      },
    },
    category: "seguridad",
    brand: "Tecnofy",
    sku: "TEC-CAM-001",
    images: [
      { src: "/images/minicamara/hero.webp", alt: "Mini Cámara WiFi de Seguridad Tecnofy" },
      { src: "/images/minicamara/offer.webp", alt: "Mini Cámara WiFi vista frontal" },
    ],
    gallery: [
      { src: "/images/minicamara/detail-1.webp", alt: "Cámara compacta", label: "Ultra compacta" },
      { src: "/images/minicamara/detail-2.webp", alt: "Visión nocturna", label: "Visión nocturna HD" },
    ],
    benefits: [
      { text: "Ultra compacta y discreta" },
      { text: "Visión nocturna infrarrojo" },
      { text: "Detección de movimiento" },
      { text: "App gratuita (iOS / Android)" },
      { text: "WiFi sin cables" },
      { text: "Instalación en segundos" },
    ],
    features: [
      {
        title: "Vigilancia HD desde tu celular",
        description: "Calidad 1080p con visión nocturna por infrarrojo. Ve todo claramente en tiempo real desde la app, incluso en total oscuridad.",
        icon: "👁️",
      },
      {
        title: "Alertas al detectar movimiento",
        description: "La cámara detecta movimiento y te envía una notificación al instante. Nunca te pierdas nada importante.",
        icon: "⚡",
      },
      {
        title: "Sin cables, sin complicaciones",
        description: "Se conecta a tu red WiFi en un solo paso. Batería interna de larga duración o conexión directa a corriente para uso 24/7.",
        icon: "📶",
      },
      {
        title: "Seguridad 24/7 sin sorpresas",
        description: "Apagado inteligente, grabación continua y almacenamiento en la app. Todo monitoreado desde tu celular sin costos extra.",
        icon: "🛡️",
      },
    ],
    specs: [
      { label: "Resolución", value: "HD 1080p", icon: "📹" },
      { label: "Conectividad", value: "WiFi 2.4GHz", icon: "📶" },
      { label: "Visión nocturna", value: "Infrarrojo", icon: "🌙" },
      { label: "Almacenamiento", value: "Micro SD / App", icon: "💾" },
      { label: "Alimentación", value: "Batería / USB", icon: "🔋" },
      { label: "Tamaño", value: "Ultra compacta", icon: "📏" },
    ],
    testimonials: [
      { name: "Jorge R.", location: "Santiago", rating: 5, text: "La instalé en mi local y ahora puedo revisar todo desde el celular. La visión nocturna es excelente, se ve todo clarito." },
      { name: "María P.", location: "Valparaíso", rating: 5, text: "Mi preocupación era la bodega. Con esta cámara la monitoreo desde la casa y me avisa cuando hay movimiento. Super práctica." },
      { name: "Roberto L.", location: "Concepción", rating: 5, text: "Compré 2: una para el garage y otra para el patio. La app es súper fácil y el envío llegó rápido. Muy recomendada." },
    ],
    faqs: [
      { question: "¿Necesita internet fijo o solo WiFi?", answer: "Solo necesita conexión WiFi. No requiere cable de datos ni internet fijo. Se conecta a tu red WiFi hogareña o de tu negocio y listo." },
      { question: "¿Graba de noche? ¿Cómo es la visión nocturna?", answer: "Sí, tiene visión nocturna con infrarrojo. Graba y transmite en calidad HD incluso en total oscuridad. Puedes ver todo claramente desde la app." },
      { question: "¿Cuánto dura la batería?", answer: "Tiene batería interna de larga duración que puede funcionar varias horas de forma inalámbrica, o puedes conectarla a corriente continua para uso 24/7." },
      { question: "¿Cuánto demora el envío?", answer: "El envío demora entre 3 a 7 días hábiles dependiendo de tu región. Hacemos envíos a todo Chile sin excepción." },
      { question: "¿El envío es realmente gratis a todo Chile?", answer: "Sí, el envío es 100% gratis a todo Chile. Sin costos ocultos, sin sorpresas. El precio que ves es el precio final que pagas." },
      { question: "¿Tiene garantía?", answer: "Sí, todos nuestros productos tienen 3 meses de garantía. Si tienes algún problema con la cámara, nos contactas y la resolvemos." },
    ],
    painPoints: [
      { icon: "🏠", title: "Hogar sin vigilancia", description: "No puedes estar en todos lados al mismo tiempo para proteger lo que más quieres" },
      { icon: "📦", title: "Bodega desprotegida", description: "Tu bodega o local comercial necesita monitoreo constante sin contratar seguridad" },
      { icon: "🐾", title: "Mascotas sin supervisión", description: "Quieres ver cómo están tus mascotas mientras estás fuera de casa" },
      { icon: "👴", title: "Familiares mayores", description: "Necesitas saber que tus seres queridos están seguros cuando no puedes estar ahí" },
    ],
    howItWorks: [
      { step: 1, title: "Instala", description: "Coloca la cámara donde necesites vigilancia. Es tan pequeña que pasa desapercibida." },
      { step: 2, title: "Conecta WiFi", description: "Descarga la app gratuita, conecta la cámara a tu red WiFi en un solo paso." },
      { step: 3, title: "Monitorea desde tu celular", description: "Ve en tiempo real desde cualquier lugar. Recibe alertas al detectar movimiento." },
    ],
    stock: 38,
    status: "active",
    tags: ["seguridad", "camara", "wifi", "vigilancia", "hogar", "negocio", "1080p", "vision nocturna"],
    seo: {
      title: "Mini Cámara WiFi de Seguridad | HD 1080p Visión Nocturna — $24.990",
      description: "Protege tu hogar o negocio con mini cámara WiFi HD 1080p. Visión nocturna, detección de movimiento, app gratuita. $24.990 – Envío gratis a todo Chile – Pago contra entrega.",
      keywords: "camara seguridad, camara wifi, camara oculta, vigilancia hogar, camara compacta, 1080p, vision nocturna, envio gratis, Chile",
      ogImage: "/images/minicamara/hero.webp",
    },
    createdAt: "2026-07-18",
    updatedAt: "2026-07-18",
    heroTitle: "¿Tu hogar o negocio <span class=\"text-[var(--primary)]\">está desprotegido</span>?",
    heroTrustBadges: [
      { icon: "HD 1080p", label: "HD 1080p" },
      { icon: "Visión nocturna", label: "Visión nocturna" },
      { icon: "WiFi sin cables", label: "WiFi sin cables" },
      { icon: "App gratuita", label: "App gratuita" },
    ],
    solutionLabel: "La Solución",
    solutionTitle: "Protege lo que más <span class=\"text-[var(--primary)]\">importa desde tu celular</span>",
    solutionImageLabel: "HD 1080p · WiFi · Compacta",
    galleryTitle: "Así es tu cámara de seguridad",
    galleryDescription: "Compacta, discreta y con todo lo que necesitas para estar tranquilo",
    finalCtaTitle: "¿Listo para proteger tu hogar<br/>o negocio?",
    problemLabel: "¿Te sientes identificado?",
    problemTitle: "La seguridad de tu hogar no puede esperar",
    problemDescription: "Si no puedes estar en todos lados, necesitas una solución que vigile por ti",
    offerDescription: "Aprovecha el descuento por lanzamiento y protege lo que más quieres — envío gratis a todo Chile",
    videoDemoTitle: "Míralo en acción",
    videoDemoDescription: "Un video vale más que mil fotos — ve lo fácil que es usarla",
    videoDemo: [
      { src: "/video/minicamara/demo-1.mp4", poster: "/video/minicamara/demo-1.gif", label: "📹 Instalación y uso rápido" },
    ],
  },
  {
    id: "limpiador-dental-pro",
    slug: "limpiador-dental-pro",
    name: "Limpiador Dental Pro — Quita Sarro",
    shortDescription: "Elimina sarro y manchas con tecnología ultrasónica. Resultados visibles desde la primera aplicación. USB recargable.",
    longDescription: "El Limpiador Dental Pro utiliza tecnología ultrasónica de alta frecuencia para eliminar sarro, manchas y tártaro sin dolor y sin ir al dentista. Compacto, recargable por USB y con punta de seguridad que protege tu esmalte. Resultados visibles desde la primera sesión. Ideal para mantener tu sonrisa limpia y saludable desde la comodidad de tu hogar.",
    price: {
      normal: 45000,
      offer: 29990,
      bundle: {
        quantity: 2,
        price: 54990,
        label: "2x $54.990 (ahorras $4.990)",
      },
    },
    category: "dental",
    brand: "Tecnofy",
    sku: "TEC-DEN-001",
    images: [
      { src: "/images/limpiador-dental/hero.webp", alt: "Limpiador Dental Pro Tecnofy" },
      { src: "/images/limpiador-dental/offer.webp", alt: "Limpiador Dental Pro vista frontal" },
    ],
    gallery: [
      { src: "/images/limpiador-dental/detail-1.webp", alt: "Tecnología ultrasónica", label: "Tecnología ultrasónica" },
      { src: "/images/limpiador-dental/incluye.webp", alt: "Kit completo", label: "Kit completo incluido" },
      { src: "/images/limpiador-dental/testimonial-1.webp", alt: "Resultado real", label: "Resultado real" },
    ],
    benefits: [
      { text: "Elimina sarro en minutos" },
      { text: "Tecnología ultrasónica segura" },
      { text: "No daña el esmalte" },
      { text: "USB Recargable" },
      { text: "Compacto y portátil" },
      { text: "Punta de seguridad incluida" },
    ],
    features: [
      {
        title: "Tecnología ultrasónica de alta frecuencia",
        description: "Vibraciones de 30-50kHz que desprenden sarro y tártaro sin dolor, sin raspar y sin dañar el esmalte dental.",
        icon: "🔊",
      },
      {
        title: "Resultado visible desde la primera sesión",
        description: "Notarás la diferencia de inmediato. Sarro blando se elimina en segundos, sarro duro en pocas sesiones.",
        icon: "✨",
      },
      {
        title: "Punta de seguridad inteligente",
        description: "Punta de acero quirúrgico con punta redondeada que protege encías y esmalte. Diseñada para uso doméstico seguro.",
        icon: "🛡️",
      },
      {
        title: "Recargable y portátil",
        description: "Carga vía USB en 1 hora. Funciona más de 30 sesiones con una sola carga. Llévalo a cualquier parte.",
        icon: "🔋",
      },
    ],
    specs: [
      { label: "Tecnología", value: "Ultrasónica 30-50kHz", icon: "🔊" },
      { label: "Alimentación", value: "USB Recargable", icon: "🔋" },
      { label: "Punta", value: "Acero quirúrgico", icon: "🔧" },
      { label: "Peso", value: "120g (ultra ligero)", icon: "🏋️" },
      { label: "Carga", value: "~1 hora (USB-C)", icon: "⚡" },
      { label: "Autonomía", value: "30+ sesiones", icon: "⏱️" },
    ],
    testimonials: [
      { name: "Rubén S.", location: "Santiago", rating: 5, text: "Me sorprendió lo fácil que es usarlo. En 10 minutos tenía los dientes muchísimo más limpios. El sarro blando se va al toque.", avatar: "/images/limpiador-dental/cliente-1.webp" },
      { name: "Constanza L.", location: "Valparaíso", rating: 5, text: "Lo compré por curiosidad y ahora no puedo vivir sin él. Mis dientes se sienten como recién limpios por el dentista, pero sin el dolor del raspado.", avatar: "/images/limpiador-dental/cliente-2.webp" },
      { name: "Belén C.", location: "Concepción", rating: 5, text: "Mi dentista no lo podía creer. Le dije que me lo hacía yo en casa y me pidió el link. La punta es súper suave y no duele nada.", avatar: "/images/limpiador-dental/cliente-3.webp" },
    ],
    faqs: [
      { question: "¿Duele usar el Limpiador Dental Pro?", answer: "Para nada. La punta de seguridad está diseñada para ser suave con las encías y el esmalte. Puedes regular la intensidad según tu comodidad." },
      { question: "¿Funciona para sarro duro y blando?", answer: "Sí. El sarro blando se elimina en la primera sesión. El sarro duro (el que se ha acumulado por años) puede requerir 2-3 sesiones para eliminación completa." },
      { question: "¿Es seguro para el esmalte?", answer: "Totalmente seguro. La tecnología ultrasónica no rasca ni frota, simplemente vibra a una frecuencia que desprende el sarro sin dañar la superficie del diente." },
      { question: "¿Cuánto dura la batería?", answer: "Con una carga completa vía USB-C puedes usar más de 30 sesiones. Carga completa en aproximadamente 1 hora." },
      { question: "¿El envío es gratis a todo Chile?", answer: "Sí, el envío es 100% gratis a todo Chile. Sin costos ocultos. El precio que ves es el precio final que pagas." },
      { question: "¿Tiene garantía?", answer: "Sí, todos nuestros productos cuentan con 3 meses de garantía. Si tienes algún problema con el limpiador, nos contactas y lo resolvemos." },
    ],
    painPoints: [
      { icon: "🦷", title: "Sarro acumulado", description: "Esa capa amarillenta que se forma entre los dientes y que el cepillo no logra eliminar" },
      { icon: "😤", title: "Mal aliento persistente", description: "El sarro acumulado genera bacterias que causan halitosis que no se va ni con enjuague" },
      { icon: "🩸", title: "Encías que sangran", description: "Las encías inflamadas y que sangran al cepillarse son señal de sarro presionando el tejido" },
      { icon: "😁", title: "Sonrisa opaca y amarillenta", description: "Las manchas y el tártaro oscurecen los dientes, quitando brillo a tu sonrisa" },
    ],
    howItWorks: [
      { step: 1, title: "Carga y selecciona", description: "Cárgalo vía USB-C. Elige la intensidad que te funcione: baja para principiantes, alta para sarro duro." },
      { step: 2, title: "Aplica sobre el sarro", description: "Coloca la punta sobre la zona con sarro. La vibración ultrasónica hace todo el trabajo por ti." },
      { step: 3, title: "Enjuaga y admira", description: "Enjuaga la boca y disfruta de dientes notablemente más limpios y blancos desde la primera sesión." },
    ],
    stock: 100,
    status: "active",
    tags: ["dental", "sarro", "limpiador", "ultrasonico", "salud", "sonrisa", "blanqueamiento"],
    seo: {
      title: "Limpiador Dental Pro | Elimina Sarro con Tecnología Ultrasónica — $29.990",
      description: "Elimina sarro y manchas sin dolor con tecnología ultrasónica. USB recargable, punta de seguridad. $29.990 – Envío gratis a todo Chile – Pago contra entrega.",
      keywords: "limpiador dental, quita sarro, removedor sarro, ultrasonico dental, limpieza dental casa, sarro dientes, blanqueamiento dental, envio gratis, Chile",
      ogImage: "/images/limpiador-dental/hero.webp",
    },
    createdAt: "2026-07-19",
    updatedAt: "2026-07-19",
    heroTitle: "¿El sarro te <span class=\"text-[var(--primary)]\">está arruinando</span> la sonrisa?",
    heroTrustBadges: [
      { icon: "Tecnología ultrasónica", label: "Tecnología ultrasónica" },
      { icon: "Resultados visibles", label: "Resultados visibles" },
      { icon: "USB Recargable", label: "USB Recargable" },
      { icon: "100% seguro", label: "100% seguro" },
    ],
    solutionLabel: "La Solución",
    solutionTitle: "Una sonrisa limpia y profesional <span class=\"text-[var(--primary)]\">desde casa</span>",
    solutionImageLabel: "Ultrasónico · USB · Portátil",
    galleryTitle: "Así es tu Limpiador Dental Pro",
    galleryDescription: "Compacto, poderoso y con todo lo que necesitas para eliminar el sarro en casa",
    finalCtaTitle: "¿Listo para una sonrisa<br/>como nueva?",
    problemLabel: "¿Te identificas?",
    problemTitle: "El sarro no se va solo",
    problemDescription: "Por más que cepilles, el sarro duro y las manchas stubborn no desaparecen con un cepillo normal",
    offerDescription: "Aprovecha el descuento por lanzamiento y limpia tus dientes como en el dentista — envío gratis a todo Chile",
    videoDemoTitle: "Míralo en acción",
    videoDemoDescription: "Un video vale más que mil fotos — ve lo fácil que es limpiar tus dientes en casa",
    videoDemo: [
      { src: "/video/limpiador-dental/demo-1.mp4", poster: "/images/limpiador-dental/testimonial-3.webp", label: "🦷 Limpieza en acción" },
      { src: "/video/limpiador-dental/demo-2.mp4", poster: "/images/limpiador-dental/cliente-1.webp", label: "✨ Fácil de usar" },
    ],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getActiveProducts(): Product[] {
  return products.filter((p) => p.status === "active")
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export default products
